services:

  api:
    image: docker.io/asanaliev/pytfastapimodels:latest
    container_name: django_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/settings
      - DJANGO_SETTINGS_MODULE=settings.settings.settings
    command: uvicorn settings.settings.asgi:application --host 0.0.0.0 --port 8000
    restart: always

  frontend:
    image: docker.io/asanaliev/pytfastapimodels:latest
    container_name: streamlit_ui
    depends_on:
      - api
    ports:
      - "8501:8501"
    command: streamlit run settings/frontend/st.py --server.address 0.0.0.0
    restart: always